name: Auto-update bmcloud.m3u

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Generate bmcloud.m3u only if changed
        id: generate
        run: |
          npm install node-fetch@2
          node <<'EOF'
          const fs = require('fs');
          const fetch = require('node-fetch');

          const url = 'https://as.al/raw/NyCqwJ';
          const m3uPath = 'bmcloud.m3u';
          const logPath = 'bmcloud.log';

          (async () => {
            try {
              // Fetch raw playlist
              const data = (await (await fetch(url)).text()).trim();

              // Read previous content if exists
              const prev = fs.existsSync(m3uPath) ? fs.readFileSync(m3uPath, 'utf8').trim() : '';

              // Compare with previous content
              if (data === prev) {
                console.log("ℹ️ No changes detected.");
                require('child_process').execSync(`echo "changed=false" >> $GITHUB_OUTPUT`);
                return;
              }

              // Write new playlist
              fs.writeFileSync(m3uPath, data);

              // Append log
              const timestamp = new Date().toISOString();
              fs.appendFileSync(logPath, `\n[${timestamp}] Playlist updated\n`);

              console.log("✅ bmcloud.m3u updated");
              require('child_process').execSync(`echo "changed=true" >> $GITHUB_OUTPUT`);
              require('child_process').execSync(`echo "summary=Playlist updated" >> $GITHUB_OUTPUT`);
            } catch (err) {
              console.error("❌ Failed to fetch or write playlist:", err);
              require('child_process').execSync(`echo "changed=false" >> $GITHUB_OUTPUT`);
            }
          })();
          EOF

      - name: Commit and push if changed
        if: steps.generate.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bmcloud.m3u bmcloud.log
          git commit -m "Auto-update bmcloud.m3u [skip ci] - ${{ steps.generate.outputs.summary }}"
          git push