name: Auto-update tn.m3u

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate tn.m3u only if changed
        id: generate
        run: |
          npm install node-fetch@2
          node <<'EOF'
          const fs = require('fs');
          const fetch = require('node-fetch');

          const url = 'https://tnm3ulive-default-rtdb.asia-southeast1.firebasedatabase.app/channels.json';
          const filePath = 'tn.m3u';
          const prevData = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';

          (async () => {
            try {
              const res = await fetch(url);
              const data = await res.json();
              if (!data) {
                console.log("No channels found.");
                return;
              }

              let m3u = "#EXTM3U\n";
              const changesSummary = [];
              const newNames = [];

              // Build new M3U and track added/updated channels
              for (const id of Object.keys(data)) {
                const ch = data[id];
                if (ch.category !== "Tamil") continue;
                const name = ch.name || "Unknown";
                const logo = ch.icon || "";
                const stream = ch.stream || "";
                const group = (ch.channelType === "regional") ? "Local Channels" : ch.channelType || "Unknown";

                if (!stream) continue;

                const extinf = `#EXTINF:-1 tvg-name="${name}" group-title="${group}" tvg-logo="${logo}",${name}`;
                m3u += `${extinf}\n${stream}\n`;
                newNames.push(name);

                const prevLines = prevData.split('\n');
                const prevExtinf = prevLines.find(line => line.startsWith('#EXTINF') && line.includes(name));
                const prevStream = prevExtinf ? prevLines[prevLines.indexOf(prevExtinf) + 1] : null;

                if (!prevExtinf) {
                  changesSummary.push(`Added: ${name}`);
                } else if (prevExtinf !== extinf || prevStream !== stream) {
                  changesSummary.push(`Updated: ${name}`);
                }
              }

              // Detect removed channels
              const oldNames = prevData.split('\n').filter(line => line.startsWith('#EXTINF')).map(line => line.split(',')[1]);
              oldNames.forEach(name => {
                if (!newNames.includes(name)) {
                  changesSummary.push(`Removed: ${name}`);
                }
              });

              // Only write file if something changed
              if (changesSummary.length === 0) {
                console.log("No changes in tn.m3u. Skipping commit.");
                console.log('::set-output name=changed::false');
                return;
              }

              fs.writeFileSync(filePath, m3u);
              console.log('tn.m3u updated successfully.');
              console.log(`Changes: ${changesSummary.join('; ')}`);
              console.log('::set-output name=changed::true');
              console.log(`::set-output name=summary::${changesSummary.join('; ')}`);

            } catch (err) {
              console.error('Error fetching channels:', err);
            }
          })();
          EOF

      - name: Commit and push if changed
        if: steps.generate.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tn.m3u
          git commit -m "Auto-update tn.m3u [skip ci] - ${{ steps.generate.outputs.summary }}"
          git push