name: Generate Tamil M3U

on:
  schedule:
    - cron: '0 * * * *' # runs every hour at minute 0
  workflow_dispatch:     # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install node-fetch
        run: npm install node-fetch@2

      - name: Generate tamil.m3u
        run: |
          node -e "
          const fs = require('fs');
          const fetch = require('node-fetch');

          const channelsURL = 'https://tnm3ulive-default-rtdb.asia-southeast1.firebasedatabase.app/channels.json';
          const tokensURL = 'https://tnm3ulive-default-rtdb.asia-southeast1.firebasedatabase.app/tokens.json';

          (async () => {
            const today = new Date().toISOString().split('T')[0];
            const tokenData = await fetch(tokensURL).then(r=>r.json());
            const todayToken = tokenData?.[today]?.token;
            if (!todayToken) return console.log('No valid token today. Skipping.');

            const channels = await fetch(channelsURL).then(r=>r.json());
            let m3u = '#EXTM3U\n';
            for (const id in channels) {
              const ch = channels[id];
              if (ch.category !== 'Tamil' || !ch.stream) continue;
              m3u += `#EXTINF:-1 tvg-name=\\"${ch.name}\\" group-title=\\"Tamil\\" tvg-logo=\\"${ch.icon}\\",${ch.name}\n${ch.stream}\n`;
            }

            const filePath = 'tamil.m3u';
            let prevData = '';
            if (fs.existsSync(filePath)) prevData = fs.readFileSync(filePath, 'utf8');

            if (prevData === m3u) {
              console.log('No changes in tamil.m3u. Skipping commit.');
            } else {
              fs.writeFileSync(filePath, m3u);
              console.log('tamil.m3u updated successfully.');
              process.exit(0); // exit normally, commit step will run
            }
          })();
          "

      - name: Commit & Push M3U
        run: |
          if git diff --quiet tamil.m3u; then
            echo "No changes to commit."
          else
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add tamil.m3u
            git commit -m "Update tamil.m3u [skip ci]"
            git push
          fi
