- name: Generate tamil.m3u with token protection
  id: generate
  run: |
    npm install node-fetch@2
    node -e "
    const fs = require('fs');
    const fetch = require('node-fetch');

    const channelsURL = 'https://tnm3ulive-default-rtdb.asia-southeast1.firebasedatabase.app/channels.json';
    const tokensURL   = 'https://tnm3ulive-default-rtdb.asia-southeast1.firebasedatabase.app/tokens.json';

    (async () => {
      try {
        const today = new Date().toISOString().split('T')[0];
        const tokenData = await fetch(tokensURL).then(r=>r.json());
        const todayToken = tokenData?.[today]?.token;

        if (!todayToken) {
          console.log('No valid token for today. Skipping.');
          return;
        }

        const channels = await fetch(channelsURL).then(r=>r.json());
        let m3u = '#EXTM3U\n';
        for (const id in channels) {
          const ch = channels[id];
          if (ch.category !== 'Tamil' || !ch.stream) continue;
          m3u += `#EXTINF:-1 tvg-name=\\"${ch.name}\\" group-title=\\"Tamil\\" tvg-logo=\\"${ch.icon}\\",${ch.name}\n${ch.stream}\n`;
        }

        fs.writeFileSync('tamil.m3u', m3u);
        console.log('tamil.m3u updated successfully.');
      } catch (err) {
        console.error(err);
      }
    })();
    "
