- name: Generate tamil.m3u
  run: |
    node -e "
    const fs = require('fs');
    const fetch = require('node-fetch');

    const channelsURL = 'https://tnm3ulive-default-rtdb.asia-southeast1.firebasedatabase.app/channels.json';
    const tokensURL = 'https://tnm3ulive-default-rtdb.asia-southeast1.firebasedatabase.app/tokens.json';

    (async () => {
      try {
        const today = new Date().toISOString().split('T')[0];
        const tokenData = await fetch(tokensURL).then(r=>r.json());
        const todayToken = tokenData?.[today]?.token;
        if (!todayToken) {
          console.log('No valid token today. Skipping.');
          return;
        }

        const channels = await fetch(channelsURL).then(r=>r.json());
        let m3u = `#EXTM3U\n# Today's token: ${todayToken}\n`;

        for (const id in channels) {
          const ch = channels[id];
          if (ch.category !== 'Tamil' || !ch.stream) continue;
          m3u += `#EXTINF:-1 tvg-name=\\"${ch.name}\\" group-title=\\"Tamil\\" tvg-logo=\\"${ch.icon}\\",${ch.name}\n${ch.stream}\n`;
        }

        const filePath = 'tamil.m3u';
        let prevData = '';
        if (fs.existsSync(filePath)) prevData = fs.readFileSync(filePath, 'utf8');

        if (prevData === m3u) {
          console.log('No changes in tamil.m3u. Skipping commit.');
        } else {
          fs.writeFileSync(filePath, m3u);
          console.log('tamil.m3u updated successfully with token: ' + todayToken);
        }

      } catch (err) {
        console.error('Error generating tamil.m3u:', err);
        process.exit(1);
      }
    })();
    "