name: Auto-update Telugu playlist

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate an.m3u only if changed
        id: generate
        run: |
          npm install node-fetch@2
          node <<'EOF'
          const fs = require('fs');
          const fetch = require('node-fetch');

          const url = 'https://tnm3ulive-default-rtdb.asia-southeast1.firebasedatabase.app/channels.json';
          const filePath = 'an.m3u';
          const prevData = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';

          (async () => {
            try {
              const res = await fetch(url);
              const data = await res.json();
              if (!data) {
                console.log("No channels found.");
                return;
              }

              let m3u = "#EXTM3U\n";
              const currentChannels = [];

              for (const id of Object.keys(data)) {
                const ch = data[id];
                if (ch.category !== "Telugu") continue;
                const name = ch.name || "Unknown";
                const logo = ch.icon || "";
                const stream = ch.stream || "";
                const group = (ch.channelType === "regional") ? "Local Channels" : ch.channelType || "Unknown";

                if (!stream) continue;

                const extinf = `#EXTINF:-1 tvg-name="${name}" group-title="${group}" tvg-logo="${logo}",${name}`;
                m3u += `${extinf}\n${stream}\n`;
                currentChannels.push(name);
              }

              // Compare with previous file
              if (m3u.trim() === prevData.trim()) {
                console.log("No changes detected in an.m3u. Skipping commit.");
                console.log('::set-output name=changed::false');
                return;
              }

              fs.writeFileSync(filePath, m3u);
              console.log('an.m3u updated successfully.');
              console.log(`Updated channels: ${currentChannels.join(', ')}`);
              console.log('::set-output name=changed::true');
              console.log(`::set-output name=summary::${currentChannels.join('; ')}`);

            } catch (err) {
              console.error('Error fetching channels:', err);
            }
          })();
          EOF

      - name: Commit and push if changed
        if: steps.generate.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add an.m3u
          git commit -m "Auto-update an.m3u [skip ci] - ${{ steps.generate.outputs.summary }}"
          git push