name: Update IPTV Playlist

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 mins
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install dependencies
      run: npm install firebase-admin

    - name: Generate playlist.m3u
      run: |
        node <<'EOF'
        const fs = require('fs');
        const admin = require('firebase-admin');

        const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);

        admin.initializeApp({
          credential: admin.credential.cert(serviceAccount),
          databaseURL: "https://tamilgeo-d10d6-default-rtdb.firebaseio.com"
        });

        const db = admin.database();
        db.ref("channels").once("value").then(snapshot => {
          const data = snapshot.val();
          let playlist = "#EXTM3U\n";
          if (data) {
            const sorted = Object.values(data).sort((a,b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name));
            for (const ch of sorted) {
              playlist += `#EXTINF:-1 tvg-name="${ch.name}" group-title="${ch.category}" tvg-logo="${ch.logo}",${ch.name}\n`;
              playlist += `${ch.stream}\n`;
            }
          }
          fs.writeFileSync("playlist.m3u", playlist);
          console.log("playlist.m3u generated");
        });
        EOF

    - name: Commit and push playlist.m3u
      run: |
        git config user.name "GitHub Action"
        git config user.email "actions@github.com"
        git add playlist.m3u
        git commit -m "Update playlist.m3u" || echo "No changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
