name: Update M3U Playlist

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch: # Allow manual run

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create Firebase Service Account File
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      - name: Install Dependencies
        run: npm install firebase-admin

      - name: Generate Playlist from Firebase
        run: |
          node <<'EOF'
          const fs = require('fs');
          const admin = require('firebase-admin');

          // Initialize Firebase
          const serviceAccount = require('./firebase-service-account.json');
          admin.initializeApp({
            credential: admin.credential.cert(serviceAccount),
            databaseURL: "https://tamilgeo-d10d6-default-rtdb.firebaseio.com"
          });

          const db = admin.database();
          const ref = db.ref("channels");

          ref.once("value", (snapshot) => {
            const data = snapshot.val();
            if (!data) {
              console.log("No channels found.");
              return;
            }

            let playlist = "#EXTM3U\n";
            for (const key in data) {
              const ch = data[key];
              playlist += `#EXTINF:-1 tvg-name="${ch.name}" group-title="${ch.category}" tvg-logo="${ch.logo}",${ch.name}\n`;
              playlist += `${ch.stream}\n`;
            }

            fs.writeFileSync('playlist.m3u', playlist);
            console.log("playlist.m3u generated successfully!");
          });
          EOF

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add playlist.m3u
          git commit -m "Auto-update playlist.m3u"
          git push
