name: Update IPTV Playlist

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 min
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch channels from Firebase REST API
      run: |
        echo "Fetching channels.json..."
        curl -s "https://tamilgeo-d10d6-default-rtdb.firebaseio.com/channels.json" -o channels.json

    - name: Generate playlist.m3u
      run: |
        echo "Generating playlist.m3u..."
        node <<'EOF'
        const fs = require('fs');
        const data = JSON.parse(fs.readFileSync('channels.json'));
        let playlist = "#EXTM3U\n";

        if (data) {
          // Sort channels by category then name
          const sorted = Object.values(data).sort((a,b) =>
            a.category.localeCompare(b.category) || a.name.localeCompare(b.name)
          );

          for (const ch of sorted) {
            playlist += `#EXTINF:-1 tvg-name="${ch.name}" group-title="${ch.category}" tvg-logo="${ch.logo}",${ch.name}\n`;
            playlist += `${ch.stream}\n`;
          }
        }

        fs.writeFileSync("playlist.m3u", playlist);
        console.log("playlist.m3u generated successfully.");
        EOF

    - name: Commit & Push playlist.m3u
      run: |
        git config user.name "GitHub Action"
        git config user.email "actions@github.com"
        git add playlist.m3u
        git commit -m "Auto-update playlist.m3u" || echo "No changes"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
